#!/bin/bash

#####################################################################
# wilddiggr Memory Issue Fix Script
#
# 用途：自動修改 wilddiggr 的 DebugMode 配置以降低記憶體使用
# 作者：Claude Code Analysis
# 日期：2025-11-16
#####################################################################

set -e  # 遇到錯誤立即退出

# 顏色定義
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# 配置
REPO_URL="https://gitlab.ftgaming.cc/devops/kustomize-prd.git"
REPO_DIR="$HOME/gemini/claude-project/kustomize-prd"
CONFIG_PATH="gemini-game/overlays/prd/arcade-svc/arcade-wilddiggr-game"
NAMESPACE="wilddiggr-prd"
POD_NAME="wilddiggr-0"

# 函數：打印帶顏色的消息
print_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# 函數：檢查命令是否存在
check_command() {
    if ! command -v $1 &> /dev/null; then
        print_error "$1 未安裝，請先安裝"
        exit 1
    fi
}

# 函數：檢查 kubectl 連接
check_kubectl() {
    print_info "檢查 kubectl 連接..."
    if ! kubectl get ns $NAMESPACE &> /dev/null; then
        print_error "無法連接到 Kubernetes cluster 或 namespace $NAMESPACE 不存在"
        exit 1
    fi
    print_success "kubectl 連接正常"
}

# 函數：顯示當前記憶體使用
show_current_memory() {
    print_info "當前記憶體使用情況："
    kubectl top pod $POD_NAME -n $NAMESPACE || print_warning "無法獲取記憶體使用（metrics-server 可能未安裝）"
}

# 函數：顯示當前配置
show_current_config() {
    print_info "當前 DebugMode 配置："
    kubectl exec -n $NAMESPACE $POD_NAME -- cat /app/setting.xml 2>/dev/null | grep -o 'DebugMode="[0-9]"' || print_warning "無法讀取配置"
}

# 函數：Clone 或更新倉庫
setup_repo() {
    print_info "準備配置倉庫..."

    if [ -d "$REPO_DIR" ]; then
        print_warning "倉庫目錄已存在：$REPO_DIR"
        read -p "是否要拉取最新變更？(y/n) " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            cd "$REPO_DIR"
            git fetch origin
            git pull origin main || git pull origin master
            print_success "倉庫已更新"
        fi
    else
        print_info "Clone 倉庫..."
        cd "$(dirname "$REPO_DIR")"
        git clone "$REPO_URL" "$REPO_DIR"
        print_success "倉庫 clone 完成"
    fi

    cd "$REPO_DIR/$CONFIG_PATH"
}

# 函數：查找包含 DebugMode 的文件
find_config_file() {
    print_info "查找配置文件..."

    local config_files=$(grep -r "DebugMode" . --include="*.yaml" --include="*.yml" -l 2>/dev/null)

    if [ -z "$config_files" ]; then
        print_error "未找到包含 DebugMode 的配置文件"
        print_info "當前目錄：$(pwd)"
        print_info "嘗試列出所有 YAML 文件："
        find . -name "*.yaml" -o -name "*.yml"
        exit 1
    fi

    print_success "找到配置文件："
    echo "$config_files"

    # 返回第一個文件
    echo "$config_files" | head -1
}

# 函數：修改配置
modify_config() {
    local config_file=$1

    print_info "修改配置文件：$config_file"

    # 備份原文件
    cp "$config_file" "${config_file}.backup"
    print_info "已備份原文件：${config_file}.backup"

    # 顯示修改前的內容
    print_info "修改前："
    grep "DebugMode" "$config_file" || print_warning "未找到 DebugMode"

    # 執行替換
    if [[ "$OSTYPE" == "darwin"* ]]; then
        # macOS
        sed -i '' 's/DebugMode="1"/DebugMode="0"/g' "$config_file"
    else
        # Linux
        sed -i 's/DebugMode="1"/DebugMode="0"/g' "$config_file"
    fi

    # 顯示修改後的內容
    print_info "修改後："
    grep "DebugMode" "$config_file"

    # 確認修改
    if grep -q 'DebugMode="0"' "$config_file"; then
        print_success "配置修改成功"
        return 0
    else
        print_error "配置修改失敗"
        return 1
    fi
}

# 函數：提交變更
commit_changes() {
    print_info "提交變更到 Git..."

    cd "$REPO_DIR"

    # 檢查是否有變更
    if ! git diff --quiet; then
        print_info "檢測到以下變更："
        git diff --stat

        echo
        read -p "確認要提交並推送這些變更？(y/n) " -n 1 -r
        echo

        if [[ $REPLY =~ ^[Yy]$ ]]; then
            git add .

            # 提交
            git commit -m "fix(wilddiggr): disable DebugMode to reduce memory usage

Changes:
- Set DebugMode from 1 to 0 in wilddiggr-prd config
- This will disable verbose GORM SQL logging
- This will reduce Zap logger verbosity

Rationale:
Memory usage has reached 96.5% (965Mi/1Gi) due to excessive logging.
Analysis shows GORM SQL logging and Zap logger are the primary causes.

Impact:
- Expected memory reduction: 30-50%
- Log volume reduction: 70-80%
- No impact on error/warning logs

Generated by: scripts/wilddiggr/fix-memory-issue.sh"

            # 推送
            print_info "推送到遠端..."
            git push origin main || git push origin master

            print_success "變更已提交並推送"
        else
            print_warning "取消提交"
            return 1
        fi
    else
        print_warning "沒有檢測到變更"
        return 1
    fi
}

# 函數：監控部署
monitor_deployment() {
    print_info "等待 ArgoCD 自動同步..."
    print_info "通常需要 1-3 分鐘"

    echo
    print_info "你可以："
    echo "  1. 查看 ArgoCD UI 監控同步狀態"
    echo "  2. 執行以下命令監控："
    echo
    echo "     kubectl get application wilddiggr-prd -n argocd -w"
    echo
    echo "  3. 等待 pod 重啟後，驗證配置："
    echo
    echo "     kubectl exec -n wilddiggr-prd wilddiggr-0 -- cat /app/setting.xml | grep DebugMode"
    echo
    echo "  4. 監控記憶體使用："
    echo
    echo "     watch -n 60 'kubectl top pod wilddiggr-0 -n wilddiggr-prd'"
    echo
}

# 主流程
main() {
    echo "========================================"
    echo "  wilddiggr Memory Issue Fix Script"
    echo "========================================"
    echo

    # 檢查依賴
    print_info "檢查系統依賴..."
    check_command git
    check_command kubectl
    check_command grep
    check_command sed

    # 檢查 kubectl 連接
    check_kubectl

    # 顯示當前狀態
    show_current_memory
    echo
    show_current_config
    echo

    # 詢問是否繼續
    read -p "是否要繼續修改配置？(y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        print_info "操作已取消"
        exit 0
    fi

    # 設置倉庫
    setup_repo

    # 查找配置文件
    config_file=$(find_config_file)

    # 修改配置
    if modify_config "$config_file"; then
        # 提交變更
        if commit_changes; then
            # 監控部署
            monitor_deployment

            print_success "✅ 修復流程完成！"
            print_info "接下來請監控記憶體使用情況"
        else
            print_warning "變更未提交，可以手動執行 git 操作"
        fi
    else
        print_error "配置修改失敗"
        exit 1
    fi
}

# 執行主流程
main "$@"
